cities<-c("Beijing", 
"Cape Town",   
"Hong Kong",    
"Honolulu",     
"London",       
"Melbourne",     
"Mexico",   
"Montreal",      
"Moscow",        
"New Delhi",     
"New York",      
"Paris",         
"Rio de Janeiro",
"Rome",         
"San Francisco", 
"Singapore",     
"Stockholm",     
"Tokyo")         